# Generated by Django 4.1.2 on 2022-10-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('computer_name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('isrunning', models.BooleanField()),
                ('customer_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reportings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('comment', models.CharField(max_length=500)),
                ('reason', models.CharField(max_length=500)),
                ('process_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.process')),
            ],
        ),
    ]
