# Generated by Django 3.2.16 on 2022-10-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('process_name', models.CharField(max_length=500)),
                ('computer_name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('isrunning', models.BooleanField()),
                ('customer_name', models.CharField(max_length=500)),
            ],
        ),
    ]
