# Generated by Django 3.2.16 on 2022-11-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportings',
            name='server_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
