# Generated by Django 3.2.16 on 2022-11-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportings',
            name='robot_runtime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportings',
            name='transaction_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportings',
            name='server_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
