# Generated by Django 3.2.16 on 2022-10-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('comment', models.CharField(max_length=500)),
                ('reason', models.CharField(max_length=500)),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.process')),
            ],
        ),
    ]
