# Generated by Django 3.2.16 on 2022-10-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_process_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='computer_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='customer_name',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
